### ISSUE TITLE
Migration Notice

### ISSUE THREAD

**Issue by pzhlkj6612** [pzhlkj6612/streamlink-plugins#2]
Hi, @railannad ! Thank you for using my plugin "niconicochannelplus".

This repository is for making changes and committing them to Streamlink, not for creating new plugins. And I always forget to keep this repository synchronous with https://github.com/streamlink/streamlink, so new fixes and features cannot be seen in time. Thus, I've moved the code of "niconicochannelplus" to https://github.com/pzhlkj6612/streamlink-plugins and now I'm going to delete this repository.

Before the deletion, I'm inviting you to do some test. If there is some free time on your side, please download some live streams or videos from [ニコニコチャンネルプラス](https://portal.nicochannel.jp/) (NicoNico Channel Plus) with the **side-loading** plugin. Please give me short feedback after test.

Thanks,
Mozi (pzhlkj6612）

**Comment by nazhendenb** [comment]
Hi pzhlkj6612 .
I am glad to test it but I do not know what's mean of side-loading.

 I find the latest commit is on Jun 2 and my local file is also updated on Jun 2.
It can work normally so I think the test is not necessary
![image](https://github.com/pzhlkj6612/streamlink-fork/assets/36919867/cf14caff-990f-4cba-a8a3-881176675661)

**Comment by pzhlkj6612** [comment]
> I find the latest commit is on Jun 2 and my local file is also updated on Jun 2.
> It can work normally so I think the test is not necessary

OK.

> I am glad to test it but I do not know what's mean of side-loading.

See [Plugin sideloading - Streamlink documentation](https://streamlink.github.io/cli/plugin-sideloading.html).

Did you put the "nicochannelplus.py" file (as shown in your screenshot) into Streamlink's program directory? I suggest that you move it to "```%APPDATA%\streamlink\plugins```". If you do so, you are able to safely upgrade, downgrade or even uninstall your Streamlink.

**Comment by nazhendenb** [comment]
> > I find the latest commit is on Jun 2 and my local file is also updated on Jun 2.
> > It can work normally so I think the test is not necessary
> 
> OK.
> 
> > I am glad to test it but I do not know what's mean of side-loading.
> 
> See [Plugin sideloading - Streamlink documentation](https://streamlink.github.io/cli/plugin-sideloading.html).
> 
> Did you put the "nicochannelplus.py" file (as shown in your screenshot) into Streamlink's program directory? I suggest that you move it to "`%APPDATA%\streamlink\plugins`". If you do so, you are able to safely upgrade, downgrade or even uninstall your Streamlink.

I **moved** `niconicochannelplus.py` from `C:\Users\$USERNAME\AppData\Roaming\Python\Python38\site-packages\streamlink\plugins` to `C:\Users\$USERNAME\AppData\Roaming\streamlink\plugins` as your suggestion.  And it can download video normally.  
Is this test called  **side-loading** ?

**Comment by pzhlkj6612** [comment]
Yes, thank you!

Now let's move!

**Comment by pzhlkj6612** [comment]
Now try to upgrade your Streamlink and use the newest version:

For CMD:

```console
> pip install --user -U streamlink
```
